### ISSUE TITLE
Does Jersey 2.x JettyConnectorProvider support proxy authorization.

### ISSUE THREAD

**Issue by RachitGupta90** [eclipse-ee4j/jersey#3996]
I am trying to use JettyConnectorProvider with jersey 2.x for proxy support, but it seems that proxy authorization is not working, i have recently upgraded from Jersey 1.x to 2.x.

Please find below the code : 
ClientBuilder clientBuilder= ClientBuilder.newBuilder();
final ClientConfig config = new ClientConfig();
config.connectorProvider(new JettyConnectorProvider());
config.property(ClientProperties.PROXY_URI, proxyURI);
config.property(ClientProperties.PROXY_USERNAME, user);
config.property(ClientProperties.PROXY_PASSWORD, password);
clientBuilder.withConfig(config);
this.restClient = this.clientBuilder.build();

need help, please let me know if i am missing out something.

I can not use ApacheConnectorProvider as it has dependency on Apache HttpClient 4.x and this may require big changes for my system and this is a production issue.

**Comment by jansupol** [comment]
Jetty connector does not accept PROXY_USERNAME and PROXY_PASSWORD properties in 2.28. But you can try the [`JettyClientProperties.PREEMPTIVE_BASIC_AUTHENTICATION`](https://github.com/eclipse-ee4j/jersey/blob/0ee0533409b3b32b700f4f38f4c9c3846d38eb70/connectors/jetty-connector/src/test/java/org/glassfish/jersey/jetty/connector/AuthTest.java#L161) property. Does that help?

**Comment by RachitGupta90** [comment]
Hi @jansupol, this does not worked for proxy authentication, for now making use of ApacheConnectorProvider.

**Comment by jansupol** [comment]
Jetty connector in 2.29 (to be released soon) allows you to provide an optional JettyHttpClientSupplier:
```
new ClientConfig().register(new JettyHttpClientSupplier(httpClient))
```
where you can setup Jetty `httpClient` instance as needed.

**Comment by nc1997** [comment]
So, there isn't any other way I suppose to do this? If we do not want to create an HttpClient additionally and provide the config?

**Comment by jansupol** [comment]
First, not to confuse the terms, you do not need to create apache `HttpClient` to provide it with Jersey `ClientConfig`, you only need to properly utilize the `javax.ws.rs.client.ClientBuilder`, which creates the `javax.ws.rs.client.Client`.

If the problem is that you get the `javax.ws.rs.client.Client` provided by another party, then what *might* help you is to utilize [ClientBuilderListener](https://github.com/eclipse-ee4j/jersey/blob/master/core-client/src/main/java/org/glassfish/jersey/client/spi/ClientBuilderListener.java) service. In your implementation, you can do
```
        public void onNewBuilder(ClientBuilder builder) {
            builder.withConfig(....);
        }
```
The listener should be invoked when the `javax.ws.rs.client.Client` is created if the other party has the listener on its classpath.  The listener is rather a new feature, be sure to use the latest Jersey with it.

**Comment by jansupol** [comment]
This bug is an issue of Jersey 2.28 that did not support ClientProperties.PROXY_USERNAME for Jetty connector. It is supported with the Jetty connector now in the latest Jersey.

**Comment by jansupol** [comment]
The issue is fixed and can be closed.
