### ISSUE TITLE
Missing release notes for 2.28

### ISSUE THREAD

**Issue by alexanderkjall** [eclipse-ee4j/jersey#4042]
Release notes are normally posted on https://jersey.github.io/, but there doesn't seem to be any for release 2.28 have they moved to another location?

**Comment by jansupol** [comment]
We are aware of it. Version 2.28 is almost identical to 2.27, so please use the manual for 2.27 for few more days before we update the documentation. 

All Jakarta EE projects are supposed to have the same design documentation accessible from eclipse-ee4j.github.io/{project}, such as [javamail](https://eclipse-ee4j.github.io/javamail/) for instance.  The pages are generated from markdown files and we:
1) search for a way to incorporate the documentation Jersey generates to the documentation generated from the markdown
2) use the jersey.github.io to be redirected to the new documentation, if possible.

**Comment by senivam** [comment]
Actually release notes ARE published (2 days ago they were submitted and today they got visible on the site http://jersey.github.io/) however due to Jersey's movement to Eclipse Foundation there is a mess with web sites for Jersey's representation. That is why some delays are possible in site's updates. How ever that is not the issue for now so I'm closing it.

**Comment by alexanderkjall** [comment]
Thanks a lot! Looking forward to upgrading.
