### ISSUE TITLE
Path annotation of different methods are interfering

### ISSUE THREAD

**Issue by a13u** [eclipse-ee4j/jersey#4119]
I am using jersey 2.28 via maven and have two methods in my service class (i am using a jetty server). 

```
@GET
@Path("{Prefix}{p:/?}{id: ((\\d+)?)}/abc{p2:/?}{number: (([A-Za-z0-9]*)?)}")
public Response doAnything2() {
    return Response.ok("sdf").build();

}
```
```
/*with that code below the GET method does not work, if I remove it, it works*/
@POST
@Path("{Prefix}{p:/?}{id: ((\\d+)?)}/abc/{yeah}")
public Response doAnything3() {
    return Response.ok("sdf").build();

}
```

With Postman I try to access 
`GET **P/abc/MyNumber**`

If I remove the method `doAnything3` I can access the GET endpoint. If I leave the method I can't access the GET endpoint (Method not found error).
Please, inform me if you have troubles reproducing the error.

**Comment by jansupol** [comment]
Uri `P/abc/MyNumber` matches both `@Path("{Prefix}{p:/?}{id: ((\\d+)?)}/abc/{yeah}")` and `@Path("{Prefix}{p:/?}{id: ((\\d+)?)}/abc{p2:/?}{number: (([A-Za-z0-9]*)?)}")`. In your case, the method with `@POST` is matched first and a correct method designator (i.e. `@GET`) is not found. 

You could find a more simple example:

        @GET        
        @Path("x")
        public Response doAnything2() {
            return Response.ok("sdf").build();
        }

        @POST
        @Path("{name:[a-zA-Z][a-zA-Z_0-9]*}")
        public Response doAnything3() {
            return Response.ok("sdfa").build();
        }
In this case `POST /x` will not get matched.

The issue here is that you have two different `@PATH`s each matching the request, but the paths are not equal. 

Unfortunately, you could have a resource with many resource locators, each would lead to another locator only to eventually find the method designator differs from the request type. Then, backtracking would need to be implemented to fallback to the previous resource locator and to try a different path.

For various performance reasons, it was decided the backtracking is not to be implemented and your example is (not) working as designed.

**Comment by a13u** [comment]
So even if the method (get,Post) is different, the Path Matches?

Von meinem iPhone gesendet

**Comment by jansupol** [comment]
I am starting to think the way it was designed is not completely correct. The method selection is described by JAX-RS Spec. Section 3.7. In Step 2, both methods should be taken to Step 3, where the method with the wrong method designator should be removed.

**Comment by a13u** [comment]
I agree :)


Am 14.05.2019 21:52, schrieb jansupol:

**Comment by jansupol** [comment]
This seems to work as described by the Request Matching Algorithm.  Step 2.f sorts the resource methods, but since the sorting criterium is equal for both resource methods, step 2.g selects the first. 

That being said, I think the algorithm allows for picking a correct resource in both your cases, but not requires to pick both. The algorithm does not allow for choosing a resource locator with an equal path (for instance for PUT), though.
