### ISSUE TITLE
Duplicate if/then in NettyResponseWriter

### ISSUE THREAD

**Issue by ljnelson** [eclipse-ee4j/jersey#4142]
Hello; I happened to be reading through this code and ran across this:

https://github.com/eclipse-ee4j/jersey/blob/e2ee2e2d6da4dbb3a4c0f5417c621f402d792280/containers/netty-http/src/main/java/org/glassfish/jersey/netty/httpserver/NettyResponseWriter.java#L122-L126

Rather than simply ignoring it, I wanted to make sure it was recorded.  To my eyes, the `if`/`then` is unnecessary unless I've truly missed something.

**Comment by senivam** [comment]
The change was introduced while fixing issue JERSEY-3163 (NettyResponseWriter must not close the connection/channel on every request). Exists since 2.25.x . 

The issue was fixed correctly however author seems to overlooked duplicate in IF/ELSE clause.

I would keep the only line 
`ctx.write(new HttpChunkedInput(jerseyChunkedInput)).addListener(FLUSH_FUTURE);`
there

**Comment by jansupol** [comment]
Fixed by #4151
