### ISSUE TITLE
Using another framework for DI

### ISSUE THREAD

**Issue by mikeholler** [eclipse-ee4j/jersey#4215]
We're currently starting to use Dropwizard for our REST API re-work, which of course uses Jersey. We're also a shop that prefers Kotlin quite a bit, and as such prefer tools that work with Kotlin where possible. This includes our dependency injection framework, where we like to use [Kodein](https://kodein.org/di/).

This approach appeared to work very well for us to start by using `register(Object)` rather than `register(Class)` so we can provide our already-injected version of a component.

However, once we got into more complex use cases it started to become clear that we can't simply ignore the Jersey DI framework because we want access to things like `UriInfo` and other `RequestScoped` things. It's clear that our current solution does not seem to be working well as a result.

I've read the docs about how `ComponentProvider` and [Custom Lifecycle Management](https://jersey.github.io/documentation/latest/ioc.html#d0e17202) can be used to help create a bridge between the two frameworks, I've read about `guice-bridge`, and a bunch of other DI implementations, but I haven't found any good, clear examples and documentation for how I might achieve this goal.

The things I know I need, which I'd like to learn more about, are:

* How to attach `RequestScoped` bindings (like `UriInfo`) from HK2 to another DI framework
* How to get Jersey to use my DI graph for injection so I can use `register(Class)` instead of `register(Object)`

With these two things, I believe I can do what I want, but I don't see any documentation for how I might accomplish either.

Thank you for your time and (hopefully) your help :)

**Comment by mkarg** [comment]
I fear that HK2 is tightly integrated with Jersey, but I may be wrong. Possibly it is worth a look to check what exactly Jersey's HK2 DI module does?

In case you manage using Kodein with Jersey, it would be cool if you would donate the code in form of an Jersey DI module back to the Jersey project. :-)

**Comment by jansupol** [comment]
Since Jersey 2.26, the first step for an abstraction to DIs is implemented. The goal has been to make other DIs possible to work with Jersey. There are a few issues:
- In JAX-RS 3.0 the main DI is planned to be CDI, rather than CDI. To support this, the abstraction can evolve and it may become even harder for other DIs to become supported. JAX-RS 3.0 was planned for the next year.
-  JAX-RS specification itself demands injections that even CDI does not support at the moment. That can be changed either on CDI side, JAX-RS side, or both. However, it means the DIs, in general, could have an issue to support all the features.

That being said, I assume your use case is quite different, you do not want to support every corner case with your injection framework.  
- You can check the [spring module](https://github.com/eclipse-ee4j/jersey/tree/master/ext/spring4) for how the integration is done. Jersey asks spring about injections candidates there.
- For a request scope injections, the simplest solution seems to be to create a Filter where HK2 would inject the information and you would pass it to your framework. You would need to ensure with `@Priority` that this filter is executed first. The other solutions will be more complicated.
