### ISSUE TITLE
Backward compatibility with optional @QueryParam

### ISSUE THREAD

**Issue by sp4ce** [eclipse-ee4j/jersey#4251]
Hello,

I have an  issue that I would like to bring to the community and potential idea about how to make it better, but feel free to close it, if this is completely out of the line. Before starting please have a look at this [stack-overflow](https://stackoverflow.com/questions/57830300/add-queryparam-to-jax-rs-existing-api-in-a-backward-compatible-way-for-jerseycl) question that describes a customer pain.

When a service is adding an **optional** `@QueryParam` to its API, it seems very inconvenient to the customers of the service that they need to do anything at all in order to maintain backward compatibility, as well as receiving new version of the interface.

One of the solution I can imagine is that Jersey generate all the possible methods without the optional parameters to let the client decides to use them or not.

In an example from the JAX-RS interface
```
@Api
@Path("/resourceA")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public interface ResourceA
{
    @GET
    @Path("{id : .+}")
    A getResourceById(@PathParam("id") String id, @QueryParam("param") String param);
}
```

The Jersey client generates two methods:

```
A getResourceById(String id);
A getResourceById(String id, String param);
```

You would not be able to use the same interface `ResourceA` for the resource on the client side, but it could be some auto generated code like this.

```
@Generated
class BackwardCompatibleResourceA extends ResourceA {
    private ResourceA resource;

    A getResourceById(String id) {
        return resource.getResourceById(id, null);
    }

    A getResourceById(String id, String param) {
        return resource.getResourceById(id, param);
    }
}
```

This mean that the `BackwardCompatibleResourceA` will always be backward compatible when the interface is adding new optional `@QueryParam`.

Please let me know what to Jersey community thinks. 

Thanks,
--
Baptiste

**Comment by jansupol** [comment]
I assume this is regarding the proxy client.

The easy part:
  - Not every `@QueryParam` is optional in general, so generating the additional method should not be for every interface. The API would need to mark the param as Optional.
  - But when the API would mark the argument as optional, they can add the method without the  `@QueryParam` on their own.

The hard part:
 - The resource methods are methods from the `ResourceA` interface. If you would want additional generated method on the interface to be used by a client, you would need to generate it in compile time. Otherwise, you would not recompile the method. Perhaps an annotation processor of some kind would need to be used. Runtime bytecode manipulation would come too late.
