### ISSUE TITLE
MP-config extension fails for empty values

### ISSUE THREAD

**Issue by pa314159** [eclipse-ee4j/jersey#4725]
https://github.com/eclipse-ee4j/jersey/blob/741aad4fb064c1824325339f78d22b2a5c3dac20/ext/microprofile/mp-config/src/main/java/org/glassfish/jersey/microprofile/config/ConfigurationModel.java#L86

This line may fail if the value of the configuration is empty.

E.g. systems may set environment variables like this

> export AN_EMPTY_VARIABLE=

MP-config trims all empty values to null so the invocation of

> config.getValue("AN_EMPTY_VARIABLE", String.class)

fails with `NoSuchElementException`

**Comment by senivam** [comment]
For the record:
 MP-config empty properties handling behavior changed since MP config 2.0. Changes are described here: https://github.com/eclipse/microprofile-config/issues/446
Following PR introduced changes to code: https://github.com/eclipse/microprofile-config/pull/598/files

for us this means that we shall handle external configs' properties handling more carefully. 

Internal Jersey properties handling works without changes.
