### ISSUE TITLE
Expect100ContinueFeature documentation

### ISSUE THREAD

**Issue by huthomas** [eclipse-ee4j/jersey#5121]
I am trying to use the `Expect100ContinueFeature` for a client post request. It is currently not working as expected, and I am trying to figure out how the feature is expected to work.

In which cases is the expect header added, and is the `content-length` necessary that the header will be added?

If the header is added, is the expected behavior automatically performed by the client? Sending headers only first, wait and only send body after the status 100 response.

**Comment by senivam** [comment]
Hi @huthomas, the Expec100Continue feature works only for the default client connector. You have to register it either as a feature (`register(Expect100ContinueFeature.basic()` or `register(Expect100ContinueFeature.withCustomThreshold(...length)`) or via property (`.property(ClientProperties.EXPECT_100_CONTINUE, Boolean.TRUE)`). After, when it comes to the request, the connector checks if there is some Content-Length in the request and if the request processing is not chunked (no content length is present, the entity is being streamed). Only if those conditions are met, the Expect header is set. And another thing, is that the Content-Length shall exceed the threshold size, otherwise the entity will be sent without the Expect header. The default value for the threshold is 65536L. But it is possible to modify the value while registering the feature (see above) or by the property `ClientProperties.EXPECT_100_CONTINUE_THRESHOLD_SIZE`

**Comment by huthomas** [comment]
Hi @senivam , thx for the info.

I am trying to create a post request with `FormDataMultiPart` body. So the content-length is not set by default. Is there a recommended way to configure the client target for a `FormDataMultiPart` body?

And if the header is added by the `Expect100ContinueFeature` the default client connector will handle the expected behavior by sending headers, wait for response and send body if response status is 100? I am asking because I could not find the code for that.

**Comment by senivam** [comment]
regarding `FormDataMultiPart`, probably you are trying to upload files to server, so basically, the Content-Length header would be the sum of all uploaded files, like:
```
long size = 0;
for (final BodyPart part : entity.getBodyParts()) {
      size += part.getContentDisposition().getSize();
}
```
but you can count the whole length in any other convenient way. 
And then set it to the request `...request().header(HttpHeaders.CONTENT_LENGTH,size)`.

regarding the 2nd part of your question - yes, the default client connector handles the expected behavior when the `Expect` header is set.

**Comment by huthomas** [comment]
Thanks for the clarifications.

Instead of calculation the `CONTENT_LENGTH`, I had to set the property `REQUEST_ENTITY_PROCESSING` to `CHUNKED` as the content of the `FormDataMultiPart` are multiple `InputStreams`.
