### ISSUE TITLE
Bogus license information in the "core-server" pom.xml file

### ISSUE THREAD

**Issue by waynebeaton** [eclipse-ee4j/jersey#5158]
The `pom.xml` file in the core-server component includes the following [passage](https://github.com/eclipse-ee4j/jersey/blob/7b6d2f84391f24310baae7d8e55e644703642826/core-server/pom.xml#L51):

````
<license>
    <name>Apache License, 2.0</name>
    <url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
    <distribution>repo</distribution>
    <comments>Dropwizard Monitoring inspired classes @ org.glassfish.jersey.server.internal.monitoring.core</comments>
</license>
````

AFAICT, this refers to content [here](https://github.com/eclipse-ee4j/jersey/tree/master/core-server/src/main/java/org/glassfish/jersey/server/internal/monitoring/core). This content was contributed to the project via [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16155) in which the committer indicated that the content was "inspired" by another implementation, but did not contain any actual content from the cited implementation. Further, the project content contains a standard project copyright and license header indicating (I believe correctly) that the content is distributed under the project's default licensing terms.

I believe that the Apache-2.0 reference in the pom.xml is actually incorrect. Is my assessment correct?

/cc @ivargrimstad @jansupol

**Comment by jansupol** [comment]
The ASL 2.0 license is there since the contribution of Jersey to the Eclipse Foundation. The Oracle legal department was strict about the need to have the ASL there, and as such, it was contributed to the Eclipse Foundation. 

Should Eclipse Legal come and say this MUST be an EPL 2.0 license, the project can change that. However, it is not quite clear to me why. Let us skip this part, which is maybe could have been an EPL 2.0 license, since the code is not exactly the same as the DropWizard code, and move forward to another example for a while.

Jersey repackages classes from hibernate-validator. Hibernate-validator uses ASL 2.0 and Jersey repackages the hibernate-validator classes with ASL 2.0 license. The classes are in a separate [hibernate ](https://github.com/eclipse-ee4j/jersey/tree/master/ext/bean-validation/src/main/java/org/glassfish/jersey/server/validation/internal/hibernate) package (similarly to the DropWizard classes, the classes are in a separate package). We made a [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21874) for it using ASL 2.0. It has been approved, too. Is it not the same situation as with the DropWizard-inspired classes?

**Comment by jansupol** [comment]
Please note that the Third Party content used in Jersey is clearly marked in the [NOTICE.md](https://github.com/eclipse-ee4j/jersey/blob/master/NOTICE.md) file.

**Comment by jansupol** [comment]
Closing as the discussion does not seem to continue.
