### ISSUE TITLE
Can we bump hk2 version to 3.0.x?

### ISSUE THREAD

**Issue by Shoothzj** [eclipse-ee4j/jersey#5268]
Hello community. I would like to inquire if it is possible to upgrade the HK2 API to version 3.0.x. I am willing to assist in any way I can to help with the upgrade process.

Thank you for your time and consideration.

**Comment by senivam** [comment]
Hello @Shoothzj , the 3.0.x and 3.1.x versions of Jersey already use the latest (3.0.3) version of the HK2 API. For the 2.x (master) versions of Jersey it's not possible because of compatibility (Jakarta EE8 vs Jakarta EE9/10). So, you can take a look at versions of Jersey that correspond to your requirements - 3.0.x is for Jakarta EE9 and 3.1.x is for Jakarta EE10.

**Comment by Shoothzj** [comment]
@senivam  Thanks for your reply. :)
