### ISSUE TITLE
Test failures after migration to Jersey 3.1.1

### ISSUE THREAD

**Issue by sergey-morenets** [eclipse-ee4j/jersey#5295]
Hi

We've just migrated from Jersey 3.0.3 to 3.1.1 and noticed that most of our Jersey-related integration tests started failing with 404 error.
Our investigation figured out that cause of this issue is this commit - https://github.com/eclipse-ee4j/jersey/commit/a83c7cd008fc22dd8b18ecce5f30636e3a578813

Previously Jersey Grizzly 2 container didn't use path value from @ApplicationPath so we provided "orders" relative path in the tests using WebTarget object. 
But in Jersey 3.1.x application path is actually used:

```
final String appPath = handler.getApplicationHandler().getConfiguration().getApplicationPath();
final String uriPath = appPath == null ? uri.getPath() : uri.getPath() + "/" + appPath;
```

So we have to update tests and include application path: "api/orders".

This seems to be breaking change but it's never mentioned in the Jersey documentation ("Migration Guide" section) - https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest31x/migration.html

**Comment by jansupol** [comment]
It's more a fixed bug, Jersey 2.x and 3.0.x did not support `@ApplicationPath` by other then `Servlet` container, but they should have. Jersey 3.1 do implement it, but it was not backported to older versions, not to break anything.

Right, we should mention it in doc.

**Comment by tusharg1t** [comment]
Hi,
A small doubt is that, in this commit - https://github.com/eclipse-ee4j/jersey/commit/a83c7cd008fc22dd8b18ecce5f30636e3a578813
The appPath is directly appended to uri path. I get it that you want to append the app path like "/api/v1/" to the uri path like"user/list" 
but 
What if app path is "/\*" in that case the final uri turns out to be "/\*/user/list" instead of "/user/list"

In Jakrta ws.rs-api @ApplicationPath("/*") is used to annotate the application path.

I think there should be a validation for this also! or is there a version which addressed this issue?
