### ISSUE TITLE
Jersey 3.0.x has no working provider that support Java 17, PATCH, and multipart attachments

### ISSUE THREAD

**Issue by dude-abides** [eclipse-ee4j/jersey#5598]
I am using Dropwizard 4 (Jersey 3.0.5) on Java 17. I have tried every provider that claims it supports PATCH and multipart. They all have one major roadblock or another.

1. HttpUrlConnectorProvider - Cannot support PATCH due the use of reflection that is restricted in Java 16+
2. JdkConnectorProvider - Works with both PATCH and multipart, but has broken error handling.
3. NettyConnectorProvider - Works with both PATCH and multipart, but does not respect timeout settings.
4. HelidonConnectorProvider - Alway return null from HelidonConnectorProvider.getConnector()

All others claim they do not support multipart attachment because header restrictions.

Am I missing something, or is this the state of this project?

**Comment by jansupol** [comment]
1. Yes, HttpUrlConnector does not support PATCH after JDK 16.
2. I do not know your use-case, so I cannot deny nor confirm.
3. You are on almost 2 years old Jersey 3.0.5. I am pretty sure that NettyConnector did not support MultiPart in 3.0.5. It does so since 3.0.12. The timeouts were tweaked during the years, although I cannot say your use-case with shutting down the server would be any different.
4. Hellidon Connector has been fixed in 3.0.7. Optionally, you can use directly Helidon Connector from Helidon w/s that we just reuse:
```
<dependency>
    <groupId>io.helidon.jersey</groupId>
    <artifactId>helidon-jersey-connector</artifactId>
    <version>3.2.7</version>
</dependency>
```

**Comment by dude-abides** [comment]
Apologies @jansupol I am frustrated. I will close this ticket and create separate tickets for Netty and Jdk.

**Comment by jansupol** [comment]
@dude-abides After a bit of testing, adding --add-opens java.base/java.net=ALL-UNNAMED to the client application allows for using the HTTP Patch with the HttpUrlConnector
