### ISSUE TITLE
Jersey 3.1.6 not closing request on Jetty earlyEOF

### ISSUE THREAD

**Issue by LarsKrogJensen** [eclipse-ee4j/jersey#5630]
I raised an issue with Jetty project that misbehaving clients causes Jetty to leak requests/connections/... to finally hit QoS limits and thus stoped responding to new client requests.

I managed to create a reproducer so that Jetty team could narrow it down to Jersey not properly closing the request under certain failure scenario.

All details and link to reproducer is in Jetty issue https://github.com/jetty/jetty.project/issues/11679

**Comment by jansupol** [comment]
I do not believe the bug is in Jersey. The `InputStream` has a strong contract, and the contract says 
>  @throws     IOException if an I/O error occurs.

Early EOF sounds exactly like an I/O error. So this is Jetty that does not follow the contract during `HttpInput#read`.

We could wrap each IO operation into a try-catch, but that's just crazy - if one method can break the contract, any method can do it, and we would need to wrap all the methods into a try-catch, every single `InputStream` and `OutputStream` method used in all the places within the project.

**Comment by LarsKrogJensen** [comment]
ok, closing

**Comment by joakime** [comment]
@jansupol Note, InputStream implementation can throw far far more than IOException.

It can throw any IllegalArgumentException, OutOfMemoryException, NullPointerException, IndexOutOfBandException, and countless more.  (check the implementation of InputStream.java in the openjdk source, and you'll find them easily.  Also note that InputStream.java uses Objects.java in many places which increases the number of RuntimeExceptions you can get)

And then there's the implementations of the InputStream class (it's abstract ya know) that can throw all manner of RuntimeException as well.
